openapi: 3.0.3
info:
  title: Todo AI Chatbot API
  description: API for integrating AI-powered chat functionality with the todo application
  version: 1.0.0
servers:
  - url: https://api.todoapp.com/v1
    description: Production server
  - url: http://localhost:8000
    description: Development server

paths:
  /api/{user_id}/chat:
    post:
      summary: Process user chat message and return AI response
      description: Handles natural language input from users and returns AI-generated responses with tool calls for task operations
      parameters:
        - name: user_id
          in: path
          required: true
          description: The ID of the user making the request
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChatRequest'
      responses:
        '200':
          description: Successful response with AI-generated text and tool calls
          content:
            application/json:
              schema:
              $ref: '#/components/schemas/ChatResponse'
        '400':
          description: Bad request - invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Unauthorized - invalid or missing authentication
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: Forbidden - user not authorized to access this resource
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      security:
        - bearerAuth: []

  /api/{user_id}/conversations:
    get:
      summary: List user's conversations
      description: Retrieve a list of conversation IDs for the authenticated user
      parameters:
        - name: user_id
          in: path
          required: true
          description: The ID of the user making the request
          schema:
            type: string
        - name: limit
          in: query
          required: false
          description: Maximum number of conversations to return
          schema:
            type: integer
            default: 20
            maximum: 100
        - name: offset
          in: query
          required: false
          description: Number of conversations to skip
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: List of user's conversations
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConversationListResponse'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Internal server error
      security:
        - bearerAuth: []

  /api/{user_id}/conversations/{conversation_id}:
    get:
      summary: Get conversation details
      description: Retrieve messages from a specific conversation
      parameters:
        - name: user_id
          in: path
          required: true
          description: The ID of the user making the request
          schema:
            type: string
        - name: conversation_id
          in: path
          required to true
          description: The ID of the conversation to retrieve
          schema:
            type: integer
      responses:
        '200':
          description: Conversation details with messages
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConversationDetailResponse'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Conversation not found
        '500':
          description: Internal server error
      security:
        - bearerAuth: []

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    ChatRequest:
      type: object
      required:
        - message
      properties:
        conversation_id:
          type: integer
          description: Optional existing conversation ID. If omitted, a new conversation will be created.
        message:
          type: string
          description: The user's message to the AI assistant
          minLength: 1
          maxLength: 2000

    ChatResponse:
      type: object
      required:
        - conversation_id
        - response
        - tool_calls
      properties:
        conversation_id:
          type: integer
          description: The ID of the conversation
        response:
          type: string
          description: The AI-generated response text
        tool_calls:
          type: array
          description: Array of tool calls executed by the AI
          items:
            $ref: '#/components/schemas/ToolCall'

    ToolCall:
      type: object
      properties:
        name:
          type: string
          description: Name of the MCP tool called
        arguments:
          type: object
          description: Arguments passed to the tool
        result:
          type: object
          description: Result of the tool execution

    ConversationListResponse:
      type: object
      properties:
        conversations:
          type: array
          items:
            $ref: '#/components/schemas/ConversationSummary'
        total:
          type: integer
          description: Total number of conversations for the user

    ConversationSummary:
      type: object
      properties:
        id:
          type: integer
          description: Conversation ID
        created_at:
          type: string
          format: date-time
          description: When the conversation was created
        updated_at:
          type: string
          format: date-time
          description: When the conversation was last updated
        last_message:
          type: string
          description: Preview of the last message in the conversation

    ConversationDetailResponse:
      type: object
      properties:
        id:
          type: integer
          description: Conversation ID
        created_at:
          type: string
          format: date-time
          description: When the conversation was created
        updated_at:
          type: string
          format: date-time
          description: When the conversation was last updated
        messages:
          type: array
          items:
            $ref: '#/components/schemas/Message'

    Message:
      type: object
      properties:
        id:
          type: integer
          description: Message ID
        role:
          type: string
          enum: [user, assistant]
          description: Who sent the message
        content:
          type: string
          description: The message content
        created_at:
          type: string
          format: date-time
          description: When the message was created

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: Error message
        code:
          type: string
          description: Error code
        details:
          type: object
          description: Additional error details