"""
MCP Tool for adding tasks to the todo list
"""
from typing import Dict, Any
import json
import requests
from dotenv import load_dotenv
import os

# Load environment variables
load_dotenv()

def add_task(user_id: str, title: str, description: str = None) -> Dict[str, Any]:
    """
    Add a new task to the user's todo list

    Args:
        user_id: The ID of the user creating the task
        title: The title of the task
        description: Optional description of the task

    Returns:
        Dict containing the result of the operation
    """
    try:
        # This is a placeholder implementation
        # In a real system, this would connect to the database
        # through an API or direct database connection

        # Validate inputs
        if not user_id or not title:
            return {
                "success": False,
                "error": "user_id and title are required"
            }

        if len(title.strip()) == 0:
            return {
                "success": False,
                "error": "title cannot be empty"
            }

        # In a real implementation, we would:
        # 1. Connect to the backend API or database
        # 2. Insert the task record
        # 3. Return the created task

        # Placeholder response
        result = {
            "success": True,
            "task": {
                "id": 123,  # This would be generated by the database
                "user_id": user_id,
                "title": title,
                "description": description or "",
                "completed": False,
                "created_at": "2026-02-06T12:00:00Z"
            }
        }

        return result

    except Exception as e:
        return {
            "success": False,
            "error": f"Failed to add task: {str(e)}"
        }


# If this script is run directly, it can be used for testing
if __name__ == "__main__":
    import sys
    if len(sys.argv) >= 3:
        result = add_task(sys.argv[1], sys.argv[2], sys.argv[3] if len(sys.argv) > 3 else None)
        print(json.dumps(result))
    else:
        print("Usage: python add_task.py <user_id> <title> [description]")